version: "2"         # required to adjust maintainability checks
checks:
  method-complexity:
    config:
      threshold: 10
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/contest.py"
plugins:
  pylint:
    enabled: true
  sonar-python:
    enabled: true